version: 2

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unparam
    - gocritic
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: motico-api

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
